### ISSUE TITLE
"Lauren's story" link outdated?

### ISSUE THREAD

**Issue by sverchkov** [OHDSI/TheBookOfOhdsi#113]
"Lauren's story" link in section [4.3.1](https://ohdsi.github.io/TheBookOfOhdsi/CommonDataModel.html#running-example-endometriosis) now just redirects to the main Endometriosis UK front page. Seems it's no longer anywhere on their website.

**Comment by schuemie** [comment]
Thanks! I'll put it on the list for the next edition

**Comment by cgreich** [comment]
The story is right there.

**Comment by schuemie** [comment]
It seems we just needed to drop the www.
