### ISSUE TITLE
Chapter 13 - PLE Edits

### ISSUE THREAD

**Issue by slseager78** [OHDSI/TheBookOfOhdsi#18]
Just a couple of minor edits and suggestions as I read through the PLE chapter:

- Sub-chapters 13.3 and 13.4 should be titled 'Implementing....' or 'Implementation of.....'not just 'Implementation.....'

- I would be inclined to make the descriptive section (section 13.1) on propensity scores a sub-chapter (but beware that 13.4.4 is already a sub-header for propensity scores)

- Having been part of the PLE workgroup at the OHDSI F2F, I can honestly say that it was a great experience being part of this collaboration.  Great use of the screenshots especially the little icons - they really help the viewer navigate through their cohort.

**Comment by schuemie** [comment]
Thanks! I've implemented the changes you recommended. I prefer to keep subsections to 3 levels max (e.g. 13.1.1), so I just bumped all design sections up one level to make propensity scores its own section.
