### ISSUE TITLE
PDF pages with both a table and a figure overflow outside margin

### ISSUE THREAD

**Issue by schuemie** [OHDSI/TheBookOfOhdsi#24]
For example the "The cohort method design" section in the PLE chapter

**Comment by schuemie** [comment]
This seems to be discussed [here](https://tex.stackexchange.com/questions/276699/the-longtable-environment-pushes-content-below-it-into-the-bottom-margin-of-a-pa). The problem appears to be the longtable environment. We don't explicitly use longtable. Instead, apparently pandoc [automatically converts any markdown table to longtable](https://github.com/yihui/knitr/issues/1221#issuecomment-224611118
). 

Not sure how to solve this one.

**Comment by schuemie** [comment]
I found an ugly workaround: if we use kable to create the table, then kable will output latex tables (instead of markdown tables) when the target is latex. Pandoc doesn't apply the longtable environment to those, so the layout issue is resolved.

One downside of using kable is that by default it doesn't handle text wrapping. kableExtra::column_spec enables this when setting the column width, but should only be used for latex, or else a warning is thrown (and HTML and EPUB do wrapping just fine without column_spec).

**Comment by schuemie** [comment]
@msuchard : now that we've identified what the problem is, would you perhaps know a more elegant solution than the one described above? (And implemented [here](https://github.com/OHDSI/TheBookOfOhdsi/commit/58df6df5e92d00118c66047cdf7b63a3a300144c))?

**Comment by msuchard** [comment]
Here is a possible patch to `longtable.sty`.  I will try to carve out time to check out locally.

https://www.latex-project.org/cgi-bin/ltxbugs2html?pr=tools/3512

**Comment by msuchard** [comment]
More on the discussion:

https://tex.stackexchange.com/questions/203629/longtable-and-floats-wrong-table-breaks-on-pages-with-floats-part-2/207748#207748

https://latex.org/forum/viewtopic.php?t=25244

**Comment by schuemie** [comment]
The last of this issue was resolved when I changed the margins.
