### ISSUE TITLE
Should all citations have DOIs (if available)?

### ISSUE THREAD

**Issue by msuchard** [OHDSI/TheBookOfOhdsi#3]
Currently some citations in `PatientLevelPrediction.Rmd` have DOIs and many do not (although DOIs exist for these papers).

What should be our standard across chapters?

**Comment by schuemie** [comment]
I don't feel very strongly either way. What would be a strong argument for forcing people to provide DOIs?

**Comment by vojtechhuser** [comment]
I would not require it.  (better to look for a bot that adds them to the .bib file smartly)
