### ISSUE TITLE
Exercises?

### ISSUE THREAD

**Issue by schuemie** [OHDSI/TheBookOfOhdsi#4]
The patient-level prediction chapter draft currently doesn't have any exercises . Do we think chapters should have those, for example to be used in classroom settings?

@PRijnbeek ?

**Comment by pbr6cornell** [comment]
I vote 'yes' to exercises, though it likely requires the pre-requisite of
us developing a common dataset to use throughout the book, for which the
exercises can be applied and reproducible output can be generated.
