### ISSUE TITLE
question about / 10.7.1 Exposure cohort

### ISSUE THREAD

**Issue by clarkevans** [OHDSI/TheBookOfOhdsi#59]
Hello.  I was just scanning the chapter on SQL and was looking at  [10.7.1 Exposure cohort](https://ohdsi.github.io/TheBookOfOhdsi/SqlAndR.html#exposure-cohort).  There are two discrepancies.

First, the text below says _We take the first drug exposure per person_ but in fact, the SQL does not do exactly this -- it constructs a synthetic structure having the minimal begin and minimal dates for the given person that match the concept criteria.  Now, this might be a case if exposures do not intersect.

Second, the SQL here doesn't do what the corresponding auto-generated SQL does.  The auto-generated SQL for drug exposure criteria handles the possibility of a `NULL` end-date,
```COALESCE(C.drug_exposure_end_date, (C.drug_exposure_start_date + 1*INTERVAL'1 day'))```, it also has slightly different logic, it ensures the `end_date` is within the observation period.  This may not be relevant.

**Comment by clarkevans** [comment]
It seems this entire example was removed.  Closing.

**Comment by schuemie** [comment]
Thanks @clarkevans ! The example wasn't removed, just someone forgot a closing curly bracket somewhere earlier in the book causing all subsequent chapters to be rendered inaccurately.

I've now adapted the example as you suggested.

**Comment by clarkevans** [comment]
Martijn,

I'm not sure why PARTITION BY is used so much in the SQL logic
generated by OHDSI.  However, I think it may be unnecessary in this
case... something like this should also work (untested)...

```
SELECT 1 AS cohort_definition_id,
  cohort_start_date,
  cohort_end_date,
  subject_id
FROM (
  SELECT drug_exposure_start_date AS cohort_start_date,
    COALESCE(drug_exposure_end_date,
             DATEADD(DAY, 1, drug_exposure_start_date)
    ) AS cohort_end_date,
    person_id AS subject_id
  FROM @cdm_db_schema.drug_exposure
  INNER JOIN @cdm_db_schema.concept_ancestor
    ON drug_concept_id = descendant_concept_id
  WHERE ancestor_concept_id IN (1335471, 1340128, 1341927,
    1363749, 1308216, 1310756, 1373225, 1331235, 1334456,
    1342439) -- ACE inhibitors
  ORDER BY drug_exposure_start_date
  LIMIT 1
) first_exposure 
```

**Comment by clarkevans** [comment]
Also, as I recall, in the generated logic, the the final cohort_end_date
is chosen to be the MINIMUM of  cohort_end_date and observation_period_end_date

**Comment by clarkevans** [comment]
For hand-crafted SQL, this could probably be reduced much further... here's untested.
This relies upon non-standard LEAST function which could be portable handled, it
works on PostgreSQL and MySQL.  Translation to MSSQL isn't that challenging.

```
SELECT 1 AS cohort_definition_id,
       e.drug_exposure_start_date AS cohort_start_date,
       LEAST(p.observation_period_end,
           COALESCE(e.drug_exposure_end_date,
               DATEADD(DAY, 1, e.drug_exposure_start_date)
       ) AS cohort_end_date,
    e.person_id AS subject_id
  FROM @cdm_db_schema.drug_exposure AS e
  WHERE EXISTS (
     SELECT 1 
       FROM @cdm_db_schema.concept_ancestor AS a
       ON e.drug_concept_id = a.descendant_concept_id
      WHERE a.ancestor_concept_id IN (1335471, 1340128,
          1341927, 1363749, 1308216, 1310756, 1373225, 
          1331235, 1334456, 1342439)) -- ACE inhibitors
  INNER JOIN @cdm_db_schema.observation_period p
     ON e.person_id = p.person_id
  WHERE p.observation_period_end_date >
        e.drug_exposure_start_date
    AND DATEDIFF(DAY,
            p.observation_period_start_date,
            e.drug_exposure_start_date) >= 365;
```
