### ISSUE TITLE
Need chapters about mapping, but not sure where

### ISSUE THREAD

**Issue by cgreich** [OHDSI/TheBookOfOhdsi#6]
Right now, we have a chapter about Usagi. That needs to be complemented with specific mapping processes we developed. Maybe like this:

Mapping and QA of codes to Standard Concepts

- Mapping codes locally versus through the OHDSI Standard Vocabularies
- Usagi
- Systematic mapping of Drug codes
- Systematic mapping of Condition codes
- Systematic mapping of Procedure codes
- Systematic mapping of other codes

Thoughts

**Comment by schuemie** [comment]
Currently it's in [the ETL chapter](https://ohdsi.github.io/TheBookOfOhdsi/ExtractTransformLoad.html), but I can imagine code mapping being its own chapter. In that case, I would probably put the chapter after the ETL chapter.
