### ISSUE TITLE
perhaps use drug_era for exposure cohort

### ISSUE THREAD

**Issue by clarkevans** [OHDSI/TheBookOfOhdsi#67]
For the [exposure cohort](https://ohdsi.github.io/TheBookOfOhdsi/SqlAndR.html#exposure-cohort) consider using `drug_era` rather than occurrence?  I suggest this since a bulk of this query is focused on normalizing for overlapping medications, which is something that `drug_era` does already (it is some sort of calculated table, no?).   In particular, even as written, with overlapping drug_exposures, this query is now going to grab which ever end_date happens to be first...

**Comment by schuemie** [comment]
Yes, I think you're right. My knee-jerk reaction is to prefer the DRUG_EXPOSURE table because I've seen plenty of sites that don't have their DRUG_ERA logic in order, so I don't fully trust it. But that is a different discussion. Best practices here would be to use DRUG_ERA.
